# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0003_auto_20140917_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegateway',
            name='address',
            field=models.GenericIPAddressField(default=b'127.0.0.1', verbose_name=b'Address'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='device',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensordata.Device'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='gateway',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensordata.DeviceGateway'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensordata.Location'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='physical_signal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensordata.PhysicalSignal'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_instance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='server_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
