# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0004_auto_20160525_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='callibration',
        ),
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='max_range',
        ),
        migrations.RemoveField(
            model_name='device',
            name='min_range',
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='callibration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='max_range',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='min_range',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensordata.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='units',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensordata.Units'),
        ),
    ]
