# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0005_auto_20160525_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstance',
            name='update_rate_max',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name=b'Max Update Interval [sec]'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='active',
            field=models.BooleanField(default=True, verbose_name=b'Device Active'),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='private',
            field=models.BooleanField(default=False, verbose_name=b'Private, only visible to owner'),
        ),
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.TextField(default=None),
        ),
    ]
